### PR TITLE
Added hamburger options in mobile menu

### PR DESCRIPTION
**Pull request by Rana-Mudassir**
- Updated The toggle Icon. Added onclick() function on it.
- Added javascript in the index file. 
- Updated the styling

### CODE REVIEW

**Review by anagudelogu — COMMENTED** [review]
Hi @Rana-Mudassir , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the correct linter setup, you added a `.eslintrc.json` locally, but you didn't update the `.github/workflows/linters.yml` file, kindly follow this [step-by-step tutorial](https://github.com/microverseinc/linters-config) and re-submit your project! 🤖 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Rana-Mudassir** [comment]
> Hi @Rana-Mudassir ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that doesn't have the correct linter setup, you added a `.eslintrc.json` locally, but you didn't update the `.github/workflows/linters.yml` file, kindly follow this [step-by-step tutorial](https://github.com/microverseinc/linters-config) and re-submit your project! 🤖
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Rana-Mudassir** [comment]
Hello Anagudelogu, By mistake I clicked on close pull request.
I added the yml file, But It is giving an error
eslint

**Comment by Rana-Mudassir** [comment]
Hello Anagudelogu, By mistake I clicked on close pull request. It is closed
.
I created a new pull request.I added the yml file, But It is giving an
error.
[image: eslint.PNG]

**Pull request closed without merging**
